version: '3.3'
services:
  db:
    # for mac enable platform
    platform: "linux/x86_64"
    image: mysql:5.7
    restart: always
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: 'test-db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'test-user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'test-pass'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root-pass'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db-vol:/var/lib/mysql
# Names our volume
volumes:
  my-db-vol: